-- CHIQUISTRUKIS — Oracle schema (English identifiers, SB-04)
-- Source of truth for attendance: attendance_day (month is calculated)

-- USER_ACCOUNT
CREATE TABLE user_account (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50)  NOT NULL,
    password_hash   VARCHAR2(255) NOT NULL,
    role_name       VARCHAR2(30)  NOT NULL,
    is_active       CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT uk_user_account_username UNIQUE (username),
    CONSTRAINT ck_user_account_active CHECK (is_active IN ('Y', 'N'))
);

-- INSTITUTION
CREATE TABLE institution (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ugel             VARCHAR2(100) NOT NULL,
    school_name      VARCHAR2(150) NOT NULL,
    modular_code     VARCHAR2(20)  NOT NULL,
    education_level  VARCHAR2(50),
    shift_name       VARCHAR2(30),
    is_active        CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT ck_institution_active CHECK (is_active IN ('Y', 'N'))
);

-- STAFF_MEMBER
CREATE TABLE staff_member (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni               VARCHAR2(8)   NOT NULL,
    last_names        VARCHAR2(100) NOT NULL,
    first_names       VARCHAR2(100) NOT NULL,
    job_title         VARCHAR2(80)  NOT NULL,
    employment_status VARCHAR2(50),
    is_active         CHAR(1) DEFAULT 'Y' NOT NULL,
    registered_at     DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    CONSTRAINT uk_staff_member_dni UNIQUE (dni),
    CONSTRAINT ck_staff_member_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT ck_staff_member_dni_len CHECK (LENGTH(dni) = 8)
);

-- STAFF_INSTITUTION
CREATE TABLE staff_institution (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_member_id NUMBER NOT NULL,
    institution_id  NUMBER NOT NULL,
    start_date      DATE   NOT NULL,
    end_date        DATE,
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT fk_si_staff FOREIGN KEY (staff_member_id) REFERENCES staff_member (id),
    CONSTRAINT fk_si_inst  FOREIGN KEY (institution_id)  REFERENCES institution (id),
    CONSTRAINT ck_si_active CHECK (is_active IN ('Y', 'N'))
);

-- BIOMETRIC_IMPORT (carga: draft | confirmed | cancelled + period)
CREATE TABLE biometric_import (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name        VARCHAR2(255) NOT NULL,
    file_path        VARCHAR2(500),
    uploaded_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    user_account_id  NUMBER,
    status           VARCHAR2(20) DEFAULT 'draft' NOT NULL,
    period_start     DATE,
    period_end       DATE,
    total_rows       NUMBER DEFAULT 0,
    ok_rows          NUMBER DEFAULT 0,
    error_rows       NUMBER DEFAULT 0,
    matched_rows     NUMBER DEFAULT 0,
    new_rows         NUMBER DEFAULT 0,
    CONSTRAINT fk_bi_user FOREIGN KEY (user_account_id) REFERENCES user_account (id),
    CONSTRAINT ck_bi_status CHECK (status IN ('draft', 'confirmed', 'cancelled'))
);

-- BIOMETRIC_MARK
CREATE TABLE biometric_mark (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_member_id     NUMBER NOT NULL,
    biometric_import_id NUMBER,
    marked_at           TIMESTAMP NOT NULL,
    mark_type           VARCHAR2(20) NOT NULL,
    status              VARCHAR2(20) DEFAULT 'valid' NOT NULL,
    CONSTRAINT fk_bm_staff  FOREIGN KEY (staff_member_id) REFERENCES staff_member (id),
    CONSTRAINT fk_bm_import FOREIGN KEY (biometric_import_id) REFERENCES biometric_import (id),
    CONSTRAINT ck_bm_type   CHECK (mark_type IN ('entry', 'exit')),
    CONSTRAINT ck_bm_status CHECK (status IN ('valid', 'inconsistent', 'corrected'))
);

-- INCONSISTENCY
CREATE TABLE inconsistency (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mark_id        NUMBER NOT NULL,
    issue_type     VARCHAR2(40) NOT NULL,
    description    VARCHAR2(300),
    status         VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    detected_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_inc_mark FOREIGN KEY (mark_id) REFERENCES biometric_mark (id),
    CONSTRAINT ck_inc_status CHECK (status IN ('pending', 'reviewed', 'corrected'))
);

-- JUSTIFICATION
CREATE TABLE justification (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_member_id   NUMBER NOT NULL,
    start_date        DATE NOT NULL,
    end_date          DATE NOT NULL,
    norm_code         VARCHAR2(10) NOT NULL,
    with_pay          CHAR(1) NOT NULL,
    reason            VARCHAR2(300),
    support_file_path VARCHAR2(500),
    registered_by_id  NUMBER,
    registered_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    status            VARCHAR2(20) DEFAULT 'active' NOT NULL,
    CONSTRAINT fk_just_staff FOREIGN KEY (staff_member_id) REFERENCES staff_member (id),
    CONSTRAINT fk_just_user  FOREIGN KEY (registered_by_id) REFERENCES user_account (id),
    CONSTRAINT ck_just_pay CHECK (with_pay IN ('Y', 'N')),
    CONSTRAINT ck_just_status CHECK (status IN ('active', 'cancelled')),
    CONSTRAINT ck_just_dates CHECK (end_date >= start_date)
);

-- ATTENDANCE_DAY (source of truth; month is calculated)
CREATE TABLE attendance_day (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_member_id   NUMBER NOT NULL,
    attendance_date   DATE NOT NULL,
    status            VARCHAR2(30) NOT NULL,
    late_minutes      NUMBER DEFAULT 0 NOT NULL,
    justification_id  NUMBER,
    CONSTRAINT fk_ad_staff FOREIGN KEY (staff_member_id) REFERENCES staff_member (id),
    CONSTRAINT fk_ad_just  FOREIGN KEY (justification_id) REFERENCES justification (id),
    CONSTRAINT uk_ad_staff_date UNIQUE (staff_member_id, attendance_date),
    CONSTRAINT ck_ad_late CHECK (late_minutes >= 0),
    CONSTRAINT ck_ad_status CHECK (status IN (
        'present', 'late', 'absent', 'justified', 'leave', 'permission'
    ))
);

-- AUDIT_LOG
CREATE TABLE audit_log (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id NUMBER NOT NULL,
    entity_name   VARCHAR2(40) NOT NULL,
    entity_id     NUMBER NOT NULL,
    action_name   VARCHAR2(20) NOT NULL,
    old_value     CLOB,
    new_value     CLOB,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_account_id) REFERENCES user_account (id)
);
